epochs: 600
lr1: 1e-4
lr2: 1e-2
wd1: 1e-5
wd2: 1e-2
hid_dim: 2048
n_layers: 2
temp: 1.0
use_bn: false
#lam: 0.
lam: 1.0
alpha: 1.0
epoch_f: 2000
k: 15

#epochs: 50
#lr1: 1e-4
#lr2: 1e-2
#wd1: 1e-5
#wd2: 1e-2
#hid_dim: 2048
#n_layers: 2
#temp: 1.0
#use_bn: false
##lam: 0.
#lam: 1.0
#alpha: 1.0
#epoch_f: 2000
#k: 10